### ISSUE TITLE
Better documentation about New-UDMonitor\New-UDChart -Options

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#103]

**Comment by Cragdoo** [comment]
do the `DisableSort` `DefaultSortDescending` and `DefaultSortColum` options work?

**Comment by adamdriscoll** [comment]
@Cragdoo This issue was labeled incorrectly and I will make a new issue for what you just mentioned.

**Comment by ServerCare** [comment]
I agree on providing better docs (working examples) on the New-UDMonitor\New-UDChart -Options. So far these are by far the most attractive features & the charting can use better and more elaborate examples. Rather than providing one large complex solution it would help to show simple examples that only show a few features.

**Comment by adamdriscoll** [comment]
Options are now a set of cmdlets (18 of em) with most of the ChartJS options are parameters. I've added some examples to this folder: https://github.com/adamdriscoll/poshprotools/tree/master/examples/universal-dashboard/charts They are simple little examples that show off what they are named for. I'll keep adding to these examples as people ask for specifics or I run into cool use-cases.
